vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        authors:
            uri_prefix: /images/author
            upload_destination: '%kernel.project_dir%/public/images/author'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true